# 2023-03-13

# TODO: https://github.com/pypa/gh-action-pip-audit
# TODO: https://pypi.org/project/pip-audit/

name: pip-audit-05
on:
  push:
    branches:
      # - main
      - nonexistent  # avoid triggering on main
jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install virtual environment
        run: |
          set -ux
          python -V
          python -m venv zvenv
          source zvenv/bin/activate
          pip install pip -U
          pip install -r requirements-pip-audit-02.txt -U
          pip install setuptools -U  # TODO: see below
          pip freeze
          pwd
          ls -al
          ls -al /
          # ls -al /github/workspace/  # No such file or directory
          # pip install pip-audit
      - name: Scan with Pip Audit
        uses: pypa/gh-action-pip-audit@v1.0.5
        with:
          virtual-environment: zvenv/

# TODO: if you do not do pip install setuptools -U, you get:
# Name | Version | ID | Fix Versions | Description
#setuptools | 59.6.0 | GHSA-r9hx-vwmv-q579 | 65.5.1 | Python Packaging Authority (PyPA)'s setuptools is a library
# designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers
# to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a
# vulnerable Regular Expression in `package_index`. This has been patched in version 65.5.1.
#Found 1 known vulnerability in 1 package
#Error: Process completed with exit code 1.
